### ISSUE TITLE
Accept a collection as to-many relation in a resource

### ISSUE THREAD

**Issue by lode** [lode/jsonapi#3]
Right now, a `resource->add_relation()` accepts another `resource` object. It would be nice if it can accept a `collection` object as well, setting multiple ids.

**Comment by Pierozi** [comment]
Actually I need this for continue my Project.
I'm able to purpose you a PR if you want ?

**Comment by lode** [comment]
Actually, I haven't got to this because I fear it is going to be very slow.
As I also need it for my projects I working around it at the moment.

``` php
<?php

function get_to_many_relation($main_type, $relation_type, $data) {
    // collect ids
    $ids = array();
    foreach ($data as $object) {
        $ids[] = $object->id;
    }

    // build relation spec
    return array(
        'links' => array('related' => '/api/'.$main_type.'/'.$user->id.'/'.$relation_type),
        'data'  => array('type' => $relation_type, 'id' => $ids),
    );
}

$ships = models\ships::find_all();
$jsonapi->add_relation($main_type='user', $sub_type='ship', get_to_many_relation($ships));
```

As you can always add an array with the right set of data, you can just fill the relation yourself.
This method could become something I might include, but right now I feel it requires too much domain knowledge of the data you provide, so I haven't done it yet.

**Comment by Pierozi** [comment]
I got your trick by define yourself array will be apply to `primary_relationships`

But the fix are really quick, safe and fast.
I've just finished and push in my fork at branch feature/multirelation
https://github.com/Pierozi/jsonapi/commit/b0ef713ae837ac9836c09aebdce0c48f49b632b8

**Comment by lode** [comment]
That doesn't look bad for inside jsonapi indeed. However, from the callers perspective it feels awkward.

My original idea with this issue was something like this:

``` php
$user_resource = new jsonapi\resource('user', $user->id);

$ships = mysql::select("SELECT `id` FROM `ships`;");
$ship_collection = new jsonapi\collection('ship');
foreach ($ships as $ship) {
    $ship_resource = new jsonapi\resource('ship', $ship['id']);
    $ship_collection->add_resource($ship_resource);
}

$user_resource->add_relation('ship', $ship_collection);
```

That feels all ok from within jsonapi, but as you see it is a lot of code to get it arranged.

The fix you did now would change that into the following, right?

``` php
$user_resource = new jsonapi\resource('user', $user->id);

$ships = mysql::select("SELECT `id` FROM `ships`;");
foreach ($ships as $ship) {
    $ship_resource = new jsonapi\resource('ship', $ship['id']);
    $user_resource->add_relation('ship', $ship_resource);
}
```

Quite ok, but it could be simpler I would hope. I just want something like this:

``` php
$ships = mysql::select("SELECT `id` FROM `ships`;");

$user_resource = new jsonapi\resource('user', $user->id);
$user_resource->add_relation('ship', $ships); // some magic happens
```

It feels good adding your patch anyway, as it is almost a bugfix for when you would add the same kind of relation twice. But it doesn't feel like a nice interface yet.

Do you have ideas?
I'll also play with it a bit more.

**Comment by Pierozi** [comment]
The things you want is an automatic resource from a dataset right ?

I think is something can be done easily but for good practices and the future of PHP7, we need use Interface and dataset object based on this interface and not an Array result of mysql. Or in this case a magic function for convert an array into resource based on "id" mandatory and other free column.

I've build and advanced collection examples for this usecases and for relationship into included.
we can work around this example if you want.

**Comment by lode** [comment]
@Pierozi, I've implemented this issue and used your commit. It was indeed simpler than I thought.

I did include an extra argument which is needed to add multiple `resource` objects, to prevent people from doing it by accident.

You can add relations like this:

``` php
$ship = new jsonapi\resource('ship', 42);
$ship->add_data('foo', 'bar');
$jsonapi->add_relation('ship', $ship, $skip_include=false, $type=jsonapi\resource::RELATION_TO_MANY);

$ship2 = new jsonapi\resource('ship', 24);
$ship2->add_data('bar', 'baz');
$jsonapi->add_relation('ship', $ship2, $skip_include=false, $type=jsonapi\resource::RELATION_TO_MANY);

$friend1 = new jsonapi\resource('user', 42);
$friend1->add_data('foo', 'bar');

$friend2 = new jsonapi\resource('user', 24);
$friend2->add_data('bar', 'baz');

$friends = new jsonapi\collection('friends');
$friends->add_resource($friend1);
$friends->add_resource($friend2);

$jsonapi->add_relation('friends', $friends);
```

Does this work well for your use case?

_Update:_ the magic conversion from an array dataset from mysql is for me the base, not a trick. I want the method(s) to keep accepting raw array data. I'm not really fond of adding a lot of bureaucracy when we can already work with the format. If you know better and have everything in the right format, you should be able to add it.
