### ISSUE TITLE
failed to generate json: Recursion detected

### ISSUE THREAD

**Issue by ezandonai** [lode/jsonapi#48]
When i implement exception in controller, like examples:

```
$exception = new \Exception($message='user not found', $code=404);
$document = ErrorsDocument::fromException($exception);
$document->sendResponse();
```

I've got the error: `failed to generate json: Recursion detected`

I'm trying to use this on Lumen. I'm doing something wrong?

**Comment by ezandonai** [comment]
Well, looking better, I found that the problem occurs when trying to turn exceptions into a json.
This line on **Document** file. into **toJson** method.
![image](https://user-images.githubusercontent.com/14354251/88696141-3f7f2800-d0d9-11ea-84a3-bdadb38d9cd6.png)

This occurs because the _trace_ has a **Laravel\Lumen\Application** instance.
Like can be see it below:
![image](https://user-images.githubusercontent.com/14354251/88696618-dcda5c00-d0d9-11ea-8dbb-6788ace72223.png)

I don't know why or how fix this.
Somebody can help me?

**Comment by lode** [comment]
I guess the trace contains too much data to pass through `json_encode()` in a nice way.

There's two workarounds I can think of:

1. skip the trace:

```php
$options = ['includeExceptionTrace' => false];
$document = ErrorsDocument::fromException($exception, $options);
```

This completely ignores the trace and thus prevents this issue. However, you won't see any trace in the response.

2. filter the output and pass it as new input to `sendResponse()`:

```php
// get the data which would be send as response
$responseArray = $document->toArray();

// filter out what you don't want
foreach ($responseArray['errors'] as &$error) {
	if (isset($error['meta']['trace']) === false) {
		continue;
	}
	
	foreach ($error['meta']['trace'] as &$trace) {
		if (isset($trace['args']) === false) {
			continue;
		}
		
		foreach ($trace['args'] as $index => &$argument) {
			if ($argument instanceof Laravel\Lumen\Application) {
				unset($trace['args'][$index]);
			}
		}
	}
}

// convert array to json
$options = ['array' => $responseArray];
$responseJson = $document->toJson($options);

// pass custom json to send as response
$options = ['json' => $responseJson];
$document->sendResponse($options);
```

Obviously, this is more cumbersome and less performant.
